title: The Painted Porch
description: >-
  Community wiki for the Painted Porch — a Warehouse District Art Hop venue
  in Eugene, Oregon.
theme: minima
markdown: kramdown
plugins:
  - jekyll-optional-front-matter
  - jekyll-default-layout
optional_front_matter:
  enabled: true
default_layout: default
